### ISSUE TITLE
Link these notes to a markdown file as an index

### ISSUE THREAD

**Issue by dummifiedme** [sebastian-muthwill/ticktick_to_markdown#2]
I was thinking of using this code, as I was searching for a way to send my shared links or notes into my vault. It seems good, the only thing that I feel is required to have a list of links (to the notes  imported from ticktick) to be able to review quickly and even have a checkmark.

UNRELATED: Also, is there a way to sync a list of notes? I saw there are a few APIs available.

**Comment by sebastian-muthwill** [comment]
@dummifiedme if I understand right, you want to group all your notes from ticktick somehow in obsidian? 
you could set either a tag, backlink oder reference inside the config file. This will be then on each note. 
```note_header = f" \
status: #seed \n \
tags: \n \
backlinks: \n \
reference: \n \
created: {timestamp} \n \
\n \
----"
```

**Comment by dummifiedme** [comment]
Great! Seems workable! Thanks.

**Comment by dummifiedme** [comment]
@sebastian-muthwill, I looked at the code, and frankly I was doing somewhat the same with ticktick-py myself. I am glad that you had this code already written away! Makes it so much easier for me a novice. 

If you are interested, I had some thoughts.
- What if I took a note on TicktTick and it got synced away in the Vault, and I further add some content to that note in TickTick. What would happen in this case - will the original note get appended or a new note will be created (won't be allowed though)?
    - From what I can understand from the code, it would just throw an error. We can maybe modify your code to incorporate a few common and probable errors maybe. (For my case, maybe you dont even need it)
 - Is there a way we can sync a task list too in a MD file and establish a sync?

Nevertheless, I am really very thankful for your code! It is something I was looking for (to share links over to Obsidian).

**Comment by sebastian-muthwill** [comment]
@dummifiedme your ideas and thoughts are welcome. Let me split your comment in two parts.
For the "re"-creation of notes there should not occure an error or problem. Within the config file you can specify what should happen after a note is created:
```
# shall the note stay in ticktick, or shall it be completed after import
# this defaults to true because otherwise files could be created again if moved from folder
# if the file exists, it will be overwriten
ticktick_complete_note = True
```
By default this will mark the task as completed. This reflects more or less my style of work. I chunk some notes down in thicktick and want them to be stored in obsidian. I do not care about the notes in ticktick anymore. 
If you set this to `False` task will stay in ticktick and the note in obsidian will be overwritten until you mark the task as completed by yourself. Kinda one way sync.

Creating a real two way sync is a bit more complex. This means you need to check for the changed timestamps and figure out what changed in which file. Thats not really what I had in focus with this script.

**Comment by dummifiedme** [comment]
> I do not care about the notes in ticktick anymore.

Same here. I planned to keep it true as well.
I get your style and I think I am going to use it. 

I read on iPad, and it gets difficult to send my links over to vault. Thats the only thing I intended to use it for. Also, the same script could be modified to send my tasks into vault if I happen to be on iPad. THANKS!!
